version: "3.9"
services:

  #services web
  web:

    #build Dockerfile in current dir
    build: .
    
    #expose app on 5000 on machine as 8000
    ports:  
      - "8000:5000"
    
    #mount the proj dir on the host to /code inside the cont    
    volumes:    
      - .:/code

    #tell flsk run to tun in dev mode and reload the code 
    environment:  
      FLASK_ENV: development

  redis:
    image: "redis:alpine"    

